/**
 * Dictionary of error codes defined in RETS Spec 1.8
 * Reserved Error Codes: 20004..20011 and 20014..20019
 */
module.exports = {
    "0":     ["Operation successful", null],
    "10000": ["System error", "The server has detected an error with the request that prevents it from identifying the type of request, or that prevents the server from routing the request for processing. This return code MUST NOT be used when a more specific return code can be determined."],
    "20003": ["Zero Balance", "The user has zero balance left in their account."],
    "20012": ["Broker Code Required", "The user belongs to multiple broker codes and one must be supplied as part of the login. The broker list is sent back to the client as part of the login response (see section 4.6 )."],
    "20013": ["Broker Code Invalid", "The Broker Code sent by the client is not valid or not valid for the user"],
    "20022": ["Additional login not permitted", "There is already a user logged in with this user name, and this server does not permit multiple logins."],
    "20036": ["Miscellaneous server login error", "The quoted-string of the body-start-line contains text that SHOULD be displayed to the user"],
    "20037": ["Client authentication failed.", "The server requires the use of a client password (section 4.1.2 ), and the client either did not supply the correct client password or did not properly compute its challenge response value."],
    "20041": ["User-agent authentication required.", "The server requires the use of user-agent authentication (section 4.1.2 ), and the client did not supply the user-agent header values."],
    "20050": ["Server Temporarily Disabled", "The server is temporarily offline. The user should try again later"],
    "20140": ["Insecure password.", "The password does not meet the site's rules for password security."],
    "20141": ["Same as Previous Password.", "The new password is the same as the old one."],
    "20142": ["The encrypted user name was invalid.", null],
    "20200": ["Unknown Query Field", "The query could not be understood due to an unknown field name."],
    "20201": ["No Records Found", "No matching records were found."],
    "20202": ["Invalid Select", "The Select statement contains field names that are not recognized by the server."],
    "20203": ["Miscellaneous Search Error", "The quoted-string of the body-start-line contains text that MAY be displayed to the user."],
    "20206": ["Invalid Query Syntax", "The query could not be understood due to a syntax error."],
    "20207": ["Unauthorized Query", "The query could not be executed because it refers to a field to which the supplied login does not grant access."],
    "20208": ["Maximum Records Exceeded", "Operation successful, but all of the records have not been returned. This reply code indicates that the maximum records allowed to be returned by the server have been exceeded. Note: reaching/exceeding the \"Limit\" value in the client request is not a cause for the server to generate this error."],
    "20209": ["Timeout", "The request timed out while executing"],
    "20210": ["Too many outstanding queries", "The user has too many outstanding queries and new queries will not be accepted at this time."],
    "20211": ["Query too complex", "The query is too complex to be processed. For example, the query contains too many nesting levels or too many values for a lookup field."],
    "20212": ["Invalid key request [deprecated]", "The transaction does not meet the server's requirements for the use of the Key option."],
    "20213": ["Invalid Key [deprecated]", "The transaction uses a key that is incorrect or is no longer valid. Servers are not required to detect all possible invalid key values."],
    "20301": ["Invalid parameter.", "Additional information is provided in the error block."],
    "20302": ["Unable to save record on server.", null],
    "20303": ["Miscellaneous Update Error.", null],
    "20311": ["Warning Response was not given for all warnings that contained a {{response-required}}value of 2.", null],
    "20312": ["Warning Response was given for a warning that contained a resp onse-required value of 0.", null],
    "20400": ["Invalid Resource", "The request could not be understood due to an unknown resource."],
    "20401": ["Invalid Type", "The request could not be understood due to an unknown object type for the resource."],
    "20402": ["Invalid Identifier", "The identifier does not match the KeyField of any data in the resource."],
    "20403": ["No Object Found", "No matching object was found to satisfy the request."],
    "20406": ["Unsupported MIME type", "The server cannot return the object in any of the requested MIME types."],
    "20407": ["Unauthorized Retrieval", "The object could not be retrieved because it requests an object to which the supplied login does not grant access."],
    "20408": ["Resource Unavailable", "The requested resource is currently unavailable."],
    "20409": ["Object Unavailable", "The requested object is currently unavailable."],
    "20410": ["Request Too Large", "No further objects will be retrieved because a system limit was exceeded."],
    "20411": ["Timeout", "The request timed out while executing"],
    "20412": ["Too many outstanding requests", "The user has too many outstanding requests and new requests will not be accepted at this time."],
    "20413": ["Miscellaneous error", "The server encountered an internal error."],
    "20500": ["Invalid Resource", "The request could not be understood due to an unknown resource."],
    "20501": ["Invalid Type", "The request could not be understood due to an unknown metadata type."],
    "20502": ["Invalid Identifier", "The identifier is not known inside the specified resource."],
    "20503": ["No Metadata Found", "No matching metadata of the type requested was found."],
    "20506": ["Unsupported MIMEType", "The server cannot return the metadata in any of the requested MIME types."],
    "20507": ["Unauthorized Retrieval", "The metadata could not be retrieved because it requests metadata to which the supplied login does not grant access (e.g. Update Type data)."],
    "20508": ["Resource Unavailable", "The requested resource is currently unavailable."],
    "20509": ["Metadata Unavailable", "The requested metadata is currently unavailable."],
    "20510": ["Request Too Large", "Metadata could not be retrieved because a system limit was exceeded."],
    "20511": ["Timeout", "The request timed out while executing."],
    "20512": ["Too many outstanding requests", "The user has too many outstanding requests and new requests will not be accepted at this time."],
    "20513": ["Miscellaneous error", "The server encountered an internal error."],
    "20514": ["Requested DTD version unavailable.", "The client has requested the metadata in STANDARD-XML format using a DTD version that the server cannot provide."],
    "20701": ["Not logged in", "The server did not detect an active login for the session in which the Logout transaction was submitted."],
    "20702": ["Miscellaneous error.", "The transaction could not be completed. The ReplyText gives additional information."],
    "20800": ["Unknown resource", null],
    "20801": ["Invalid object type", null],
    "20802": ["Invalid identifier", null],
    "20803": ["Invalid update action", null],
    "20804": ["Invalid (inconsistent) request parameters", null],
    "20805": ["No object found (for Delete)", null],
    "20806": ["Unsupported MIME type", null],
    "20807": ["Unauthorized", null],
    "20808": ["Some objects not deleted (in case of Delete without ObjectID or UID, if some objects could not be deleted, while some were)", null],
    "20809": ["Refused: object does not meet business rules", null],
    "20810": ["FileSize too large", "Note that some servers MAY respond with HTTP status “413 – Request entity too large” if the uploaded file is larger than any acceptable limit."],
    "20811": ["Timeout", null],
    "20812": ["Too many outstanding requests", null],
    "20813": ["Miscellaneous error", null]
};
